# Generated by Django 4.0.4 on 2022-05-09 15:45

from django.db import migrations
import dynamic_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_genre_comic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='cover',
            field=dynamic_image.fields.DynamicImageField(max_length=255, upload_to='dummy'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='thumbnail',
            field=dynamic_image.fields.DynamicImageField(max_length=255, upload_to='dummy'),
        ),
    ]
