import { NextPage } from "next/types";
import Layout from "../../components/layout";
import Head from "next/head";

const Me: NextPage = () => {
  return (
    <Layout home>
      <Head>
        <title>Me</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

    </Layout>
  );
};

export default Me;