import Head from "next/head";
import { NextPage } from "next/types";
import Layout from "../components/layout";

import ComicCard from "../components/comic_card/comicCard";
import { Status, CardProps } from "../components/comic_card/comicCard";

const card_objs: CardProps[] = [
  {
    title: "Ex and Ash",
    rating: 9.8,
    status: Status.completed,
    cover: "/images/ex-and-ash.jpg",
    link: "ex-and-ash",
    latest_chapters: [1, 2],
  },
];

const Home: NextPage = () => {
  return (
    <Layout home>
      <Head>
        <title>WebComics</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      {card_objs.map((card) => (
        <ComicCard props={card} key={card.title}/>
      ))}
    </Layout>
  );
};

export default Home;
