import Head from "next/head";
import { NextPage } from "next/types";
import Layout from "../components/layout";

const Home: NextPage = () => {
  return (
    <Layout home>
      <Head>
        <title>WebComics</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

    </Layout>
  );
};

export default Home;
