import Head from "next/head";
import { NextPage } from "next/types";
import { Button, Container, FloatingLabel, Form, Row } from "react-bootstrap";
import { FocusEvent, useState } from "react";

import Layout from "../components/layout";
import styles from "../components/modals/login.module.css";

const Registration: NextPage = () => {
  const [emailError, setEmailError] = useState("");
  const [passwordError, setPasswordError] = useState("");
  const [confirmPswError, setConfirmPswError] = useState("");

  const [password, setPassword] = useState("");

  const validateEmail = (e: FocusEvent<HTMLInputElement>) => {
    const regex =
      /^(([^<>()[\].,;:\s@"]+(\.[^<>()[\].,;:\s@"]+)*)|(".+"))@(([^<>()[\].,;:\s@"]+\.)+[^<>()[\].,;:\s@"]{2,})$/i;
    const target = e.target;
    const value = target.value;

    if (!value || !regex.test(value)) {
      target.classList.add(`${styles.error}`);
      setEmailError("Insert a valid email!");
    } else {
      target.classList.remove(`${styles.error}`);
      setEmailError("");
    }
  };

  const handleChangePassword = (e: FocusEvent<HTMLInputElement>) => {
    const target = e.target;
    const regex =
      /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z])(?=.*[!@#$%^&(){}[\]:;<>,.?\/~_+\-=|\\]).{8,32}$/i;
    const value = target.value;
    setPassword(value);

    if (!value || !regex.test(value)) {
      target.classList.add(`${styles.error}`);
      setPasswordError(
        "Error: Password must contain at least one number, one uppercase or lowercase letter, one special character, and at least 8 and no more than 32."
      );
      return;
    }
    target.classList.remove(`${styles.error}`);
    setPasswordError("");
  };

  const handleChangeConfirmPsw = (e: FocusEvent<HTMLInputElement>) => {
    const target = e.target;
    const value = target.value;

    if (value !== password) {
      target.classList.add(`${styles.error}`);
      setConfirmPswError("Error: Passwords must match");
      return;
    }
    target.classList.remove(`${styles.error}`);
    setConfirmPswError("");
  };

  return (
    <Layout>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Container
        className="narrow mb-4 mt-5 p-3"
        style={{ backgroundColor: "white" }}
      >
        <Row className="items-center mb-4">
          <h2 className="font-header">Create account</h2>
        </Row>
        <Row>
          <Form action="/" noValidate>
            <Form.Text className="mb-0">
              Your username must be unique and will be visible to other users.
            </Form.Text>
            <FloatingLabel
              label="Username"
              className="mb-3"
              controlId="formUsername"
            >
              <Form.Control
                type="text"
                placeholder="Username"
                className={`validate ${styles.form} md-input`}
                required
              />
            </FloatingLabel>
            <FloatingLabel label="Email" className="mb-3" controlId="formEmail">
              <Form.Control
                type="email"
                placeholder="Email"
                className={`validate ${styles.form}`}
                required
                onBlur={validateEmail}
              />
              <Form.Text className={styles.error}>{emailError}</Form.Text>
            </FloatingLabel>
            <FloatingLabel
              label="Password"
              className="mb-3"
              controlId="formPassword"
            >
              <Form.Control
                type="password"
                placeholder="Password"
                className={`validate ${styles.form}`}
                required
                onChange={handleChangePassword}
                title="Must contain at least one number, one uppercase or lowercase letter, one special character, and at least 8 and no more than 32."
              />
              <Form.Text className={styles.error}>{passwordError}</Form.Text>
            </FloatingLabel>
            <FloatingLabel
              label="Confirm password"
              className="mb-3"
              controlId="formConfirmPassword"
            >
              <Form.Control
                type="password"
                placeholder="Confirm password"
                className={`validate ${styles.form}`}
                required
                onChange={handleChangeConfirmPsw}
              />
              <Form.Text className={styles.error}>{confirmPswError}</Form.Text>
            </FloatingLabel>
            <Form.Group
              className="mb-3 text-center"
              controlId="formLoginButton"
            >
              <Button
                type="submit"
                variant="dark"
                className="btn-block mt-3"
              >
                Create account
              </Button>
            </Form.Group>
          </Form>
        </Row>
      </Container>
    </Layout>
  );
};

export default Registration;
