# Generated by Django 4.0.4 on 2022-05-09 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('watches', models.PositiveBigIntegerField(default=0)),
                ('follows', models.PositiveBigIntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('O', 'ONGOING'), ('H', 'HIATUS'), ('C', 'COMPLETED'), ('D', 'CANCELLED')], default='O', max_length=1)),
                ('summary', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='static')),
                ('cover', models.ImageField(upload_to='static')),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(to='comics.genre')),
            ],
        ),
    ]
