# Generated by Django 4.0.4 on 2022-05-09 16:07

from django.db import migrations, models
import django.db.models.deletion
import dynamic_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_alter_comic_cover_alter_comic_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.PositiveBigIntegerField(default=0)),
                ('comic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.comic')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', dynamic_image.fields.DynamicImageField(max_length=255, unique=True, upload_to='dummy')),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.chapter')),
            ],
        ),
    ]
