# Generated by Django 4.0.4 on 2022-05-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0011_market_library'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comic',
            old_name='genres',
            new_name='genre',
        ),
    ]
