# Generated by Django 4.0.4 on 2022-05-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0013_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='title',
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_num',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
