# Generated by Django 4.0.5 on 2022-06-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0017_remove_comic_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
